[package]
name = "varuvo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["multipart"] }
calamine = "0.25.0"
rust_xlsxwriter = "0.70.0"
tempfile = "3.12.0"
tokio = { version = "1.39.3", features = ["full"] }
